#!/usr/bin/env python3
"""
P7 (referee round 4, points 1 and 7) -- a validated rule for "disclosed model
use for the writing", plus an audit of the non-writing classes.

Two jobs:
  (1) Build a high-precision regular-expression rule for writing disclosure and
      validate it against the 424 statements already labelled by hand and by
      the assistant, reporting precision and recall. A rule that reproduces the
      hand labels can then be applied to the much larger source scan without
      reading every statement.
  (2) Apply the rule to the research, unspecified, and mention classes to find
      writing disclosures the earlier classification missed. Every flagged case
      is printed for hand inspection, since a false negative in the denominator
      biases the calibration.
Output: data/p7_rule_validation.json
"""
import json, os, re

DATA = os.path.join(os.path.dirname(__file__), "..", "data")

# High-precision writing-disclosure rule. A real disclosure is a stereotyped
# sentence: an author, a named tool, an act of use, and language work. We
# require a named tool (bare "AI" is excluded, since machine-learning papers
# use it constantly), an explicit use verb, and a language-work term, all
# within one sentence.
TOOL = (r"chat-?gpt|gpt-?[0-9o]\b|openai|claude|anthropic|google gemini|"
        r"gemini (?:pro|advanced|[0-9])|llama|copilot|deepseek|qwen|"
        r"mistral ai|grok|perplexity|large language model|\bllms?\b|"
        r"generative (?:ai|artificial intelligence)|grammarly|deepl|"
        r"quillbot|writefull|trinka|paperpal|ai-assisted|\bai tools?\b|"
        r"language model|ai language|artificial intelligence \(ai\)")
# an act of editing, which is what separates a writing disclosure from a paper
# that merely discusses or applies language models
EDIT = (r"polish|proofread|proof-read|improv|enhanc|correct|\bedit|refin|"
        r"revis|rephras|reword|paraphras|translat|check|spell|"
        r"clean(?:ed|ing)? up|smooth|tidy|assist(?:ance|ed)? (?:with|in) the "
        r"(?:writ|languag|prepar)|help(?:ed)? (?:with|to) (?:writ|improv|polish)")
# the object of that editing has to be language or the authors' own document
LANGOBJ = (r"languag|grammar|grammatic|english|wording|phrasing|readab|"
           r"\btext\b|manuscript|\bpaper\b|writing|written|prose|sentence|"
           r"paragraph|typo|spelling|style|clarity|abstract|draft|"
           r"\barticle\b|composition|expression")
NEG = (r"we do not use|did not use|no ai (?:tools?|was)|without the use of|"
       r"not used for|were not generated|not generated by|no sentences were|"
       # machine-learning reproducibility-checklist boilerplate, and papers
       # that benchmark models rather than disclose using one
       r"releasing code and data|hosted model|reproducibility can also be|"
       r"we measure the performance of|frontier llms|benchmark")

SENT = re.compile(r"(?<=[.!?])\s+")


def is_writing(text):
    t = re.sub(r"\s+", " ", text.lower())
    for s in SENT.split(t):
        if len(s) > 700:
            continue
        if not re.search(TOOL, s):
            continue
        if re.search(NEG, s):
            continue
        if re.search(EDIT, s) and re.search(LANGOBJ, s):
            return True, s[:200]
    return False, None


def main():
    cls = json.load(open(os.path.join(DATA, "n1b_classified.json")))
    labels = cls["labels"]
    snips = {}
    for line in open(os.path.join(DATA, "n1b_snippets.jsonl")):
        r = json.loads(line)
        if r.get("ok") and r.get("snippets"):
            snips[r["id"]] = " ".join(s["snippet"] for s in r["snippets"][:6])

    # (1) validate against existing labels
    tp = fp = fn = tn = 0
    fn_ids, fp_ids = [], []
    for pid, rec in labels.items():
        if pid not in snips:
            continue
        truth = "writing" in rec["purposes"]
        pred, _ = is_writing(snips[pid])
        if truth and pred: tp += 1
        elif truth and not pred: fn += 1; fn_ids.append(pid)
        elif not truth and pred: fp += 1; fp_ids.append(pid)
        else: tn += 1
    prec = tp / (tp + fp) if tp + fp else 0
    rec_ = tp / (tp + fn) if tp + fn else 0
    print(f"rule validation on {tp+fp+fn+tn} labelled papers")
    print(f"  precision {prec:.3f} ({tp}/{tp+fp}), recall {rec_:.3f} ({tp}/{tp+fn})")
    print(f"  false negatives {fn}, false positives {fp}\n")

    # (2) audit non-writing classes for missed writing disclosures
    missed = []
    for pid, rec in labels.items():
        if "writing" in rec["purposes"] or pid not in snips:
            continue
        pred, ctx = is_writing(snips[pid])
        if pred:
            missed.append({"id": pid, "classes": rec["purposes"],
                           "quote": rec.get("quote", "")[:110], "context": ctx})
    print(f"non-writing papers flagged by the rule: {len(missed)}")
    for m in missed:
        print(f"  {m['id']} {m['classes']}")
        print(f"      label quote: {m['quote']}")
        print(f"      rule context: ...{m['context'][:150]}...")

    json.dump({"validation": {"tp": tp, "fp": fp, "fn": fn, "tn": tn,
                              "precision": prec, "recall": rec_,
                              "false_negative_ids": fn_ids,
                              "false_positive_ids": fp_ids},
               "missed_writing_candidates": missed},
              open(os.path.join(DATA, "p7_rule_validation.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
