#!/usr/bin/env python3
"""Stage 9: write paper/basket_table.tex, the frozen astronomy-native basket.

The discovery figure shows the structure; the words themselves belong in a
table, where a reader can check each one and reproduce the selection. Columns
are exactly the quantities the screen used, plus the held-out validation ratio
that it did not use.
"""
import json
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
from common import DATA, ROOT

OUT = os.path.join(ROOT, "paper", "basket_table.tex")


def main():
    d = pd.read_csv(os.path.join(DATA, "discovered_with_spread.csv"))
    words = json.load(open(os.path.join(DATA, "expanded_basket.json")))["words"]
    sel = d[d.word.isin(words)].sort_values("disc_ratio", ascending=False)

    rows = []
    for _, r in sel.iterrows():
        mark = "$\\star$" if r.is_seed else ""
        rows.append((r.word, mark, 100 * r.base_df, r.disc_ratio,
                     r.val_ratio, r.topic_entropy))

    # two side-by-side halves so the table fits one column of a two-column page
    half = (len(rows) + 1) // 2
    left, right = rows[:half], rows[half:]
    while len(right) < len(left):
        right.append(None)

    def cells(t):
        if t is None:
            return " & & & & "
        w, mark, bdf, dr, vr, ent = t
        return (f"\\texttt{{{w}}}{mark} & {bdf:.1f} & {dr:.2f} & "
                f"{vr:.2f} & {ent:.3f}")

    lines = [
        "% auto-generated by src/s9_basket_table.py; do not edit",
        "\\begin{deluxetable*}{lcccc|lcccc}",
        "\\tabletypesize{\\footnotesize}",
        "\\tablecaption{The frozen astronomy-native marker basket: "
        f"{len(words)} words selected from the astro-ph corpus itself. "
        "$f_0$ is the 2015--2019 document frequency (per cent of papers); "
        "$R_{\\rm disc}$ is the 2023--2024 excess over the extrapolated "
        "background, the quantity the selection ranked on; $H$ is the "
        "normalised topic entropy, required above 0.97 so that writing style "
        "is separated from subfield vocabulary. $R_{\\rm val}$ is the "
        "2025--2026 excess, computed after the list was frozen and used "
        "nowhere in the selection. Words marked $\\star$ also appear in the "
        "imported 38-word seed basket. Selection thresholds are "
        "$f_0>0.2\\%$, $R_{\\rm disc}\\ge1.6$, $H>0.97$.\\label{tab:basket}}",
        "\\tablehead{",
        "\\colhead{word} & \\colhead{$f_0$} & \\colhead{$R_{\\rm disc}$} & "
        "\\colhead{$R_{\\rm val}$} & \\colhead{$H$} & "
        "\\colhead{word} & \\colhead{$f_0$} & \\colhead{$R_{\\rm disc}$} & "
        "\\colhead{$R_{\\rm val}$} & \\colhead{$H$}}",
        "\\startdata",
    ]
    for a, b in zip(left, right):
        lines.append(f"{cells(a)} & {cells(b)} \\\\")
    lines += ["\\enddata", "\\end{deluxetable*}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(words)} words, "
          f"{int(sel.is_seed.sum())} shared with the seed basket")


if __name__ == "__main__":
    main()
